# Pandas


Pandas contain data structures and data manipulation tools designed for data cleaning and analysis.

While pandas adopt much code from NumPy, the difference is that Pandas is designed for tabular, heterogeneous data. NumPy, by difference, is best suited for working with homogeneous numerical array data.

The name Pandas is derived from the term 'panel data' (an econometrics term for multidimensional structured data sets).

Pandas has two data structures as follows:

1. A Series is a 1-dimensional labelled array that can hold data of any type (such as integer, string, boolean, float, python objects). Its axis labels are collectively called an index.
1. A DataFrame is a 2-dimensional labelled data structure with columns. It supports multiple data types.

In [4]:
# Import the numpy and pandas library

import numpy as np
import pandas as pd

## Series
Pandas Series is a one-dimensional labelled array capable of holding any data type. However, a series is a sequence of similar data types, similar to an array, list, or column in a table.

It will assign a labelled index to each item in the pd.Series. By default, each item will receive an index label from 0 to N, where N is the length of the Series minus one.


### Creating series

In [5]:
# numeric series

num = range(1,20)
num_series = pd.Series(num)
print(num_series)

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
dtype: int64

In [6]:
# object series

string = 'Hi' , 'Hello' , 'Bye'
string_series = pd.Series(string)
print(string_series)

0       Hi
1    Hello
2      Bye
dtype: object

In [7]:
# Mix series

obj = ['1', 'HI', 'Hello']
obj_series = pd.Series(obj)
print(obj_series)

0        1
1       HI
2    Hello
dtype: object

**To set index values for a series**

The index is added using the argument `index=`. The data type of the series continues to be numeric.

In [8]:
marks = [98 , 87, 85 , 87]
subject = ["Maths", "Science", "English" , "Social Science"]

marks_series = pd.Series(marks , index = subject)
print(marks_series)

Maths             98
Science           87
English           85
Social Science    87
dtype: int64

**Print the INDEX values**

In [9]:
marks_series.index

Index(['Maths', 'Science', 'English', 'Social Science'], dtype='object')

**To create a series from a dictionary**

On passing a `dict`, the index in the resulting Series will have the dict’s keys in given order.

In [10]:
# declare a dictionary
data = {'Maths': 60, 'Science': 89, 'English': 76, 'Social Science': 86}

# create a series from the dictionary
# the dictionary keys are the index names
# the dictionary values are the series values
pd.Series(data)

Maths             60
Science           89
English           76
Social Science    86
dtype: int64

**A series with missing values**

If we pass a key that is not defined, then its value will be `NaN`.

In [11]:
# create a list of subjects
subjects = ["Maths", "Science", "Art and Craft" , "Social Science"]

# declare a dictionary
data = {'Maths': 60, 'Science': 89, 'English': 76, 'Social Science': 86}

# create a series from the dictionary
marks_series = pd.Series(data, index = subjects)
marks_series

Maths             60.0
Science           89.0
Art and Craft      NaN
Social Science    86.0
dtype: float64

### Manipulating Series

**To check for null values using `.isnull`**

In [12]:
marks_series.isnull()

Maths             False
Science           False
Art and Craft      True
Social Science    False
dtype: bool

**To check for null values using `.notnull`**

In [13]:
marks_series.notnull()

Maths              True
Science            True
Art and Craft     False
Social Science     True
dtype: bool

In [14]:
# check for marks more than 75
marks_series[marks_series > 75]

Science           89.0
Social Science    86.0
dtype: float64

In [15]:
# assign 68 marks to 'Art and Craft'
marks_series['Art and Craft'] = 68
marks_series

Maths             60.0
Science           89.0
Art and Craft     68.0
Social Science    86.0
dtype: float64

**To create a series by generating numpy random numbers**

In [16]:
# create the numbers series
# generate a sequence of 20 random numbers using randint()
num = np.random.randint(1, 20, 20)
num = pd.Series(num)
num

0      8
1     15
2     11
3      5
4     14
5     14
6     12
7      6
8     16
9      9
10     7
11     8
12     3
13     8
14     8
15    14
16    18
17     5
18     3
19    18
dtype: int64

In [17]:
# (num ** 2) + 5

**To find the square of the numbers series**

In [18]:
squ = pd.Series(num **2)
squ

0      64
1     225
2     121
3      25
4     196
5     196
6     144
7      36
8     256
9      81
10     49
11     64
12      9
13     64
14     64
15    196
16    324
17     25
18      9
19    324
dtype: int64

In [19]:
aaa=squ.index = num
print(aaa)

0      8
1     15
2     11
3      5
4     14
5     14
6     12
7      6
8     16
9      9
10     7
11     8
12     3
13     8
14     8
15    14
16    18
17     5
18     3
19    18
dtype: int64

**Extracting value specifying index**

In [20]:
# obtain the value having index 5
squ[5]

5    25
5    25
dtype: int64

**To extract a range of values specifying the location**

In [21]:
# extract values having the location
# obtain the values from the 3rd position till the 6th position
# indexing starts from 0
# the 7th position is not included
squ[3: 7]

5      25
14    196
14    196
12    144
dtype: int64

**Usage of `.iloc`**

We use `.iloc` to get the values of the specified index of numbers

In [22]:
# obtain the value in the 5th position
squ.iloc[4]

np.int64(196)

In [23]:
# obtain the values from the 3rd till the 8th position
# indexing starts from 0
squ.iloc[3:9]

5      25
14    196
14    196
12    144
6      36
16    256
dtype: int64

**Sorting a numeric series**

In [24]:
# create a pandas series
age = pd.Series([23, 45, np.nan, 41, 23, 34, 55, np.nan, 34, 20])

# print values
age

0    23.0
1    45.0
2     NaN
3    41.0
4    23.0
5    34.0
6    55.0
7     NaN
8    34.0
9    20.0
dtype: float64

In [25]:
# ascending order
# sort_values: sorts the values
# ascending : if specified as True, it sorts values in ascending order (default value is True)
age.sort_values(ascending = True)

9    20.0
0    23.0
4    23.0
5    34.0
8    34.0
3    41.0
1    45.0
6    55.0
2     NaN
7     NaN
dtype: float64

In [26]:
age.sort_values()

9    20.0
0    23.0
4    23.0
5    34.0
8    34.0
3    41.0
1    45.0
6    55.0
2     NaN
7     NaN
dtype: float64

In [27]:
# arrange in descending order
# sort_values: sorts the values
# ascending : if specified as True, it sorts values in ascending order (default value is True)
# set ascending to False to sort the values in descending order
age.sort_values(ascending = False)

6    55.0
1    45.0
3    41.0
5    34.0
8    34.0
0    23.0
4    23.0
9    20.0
2     NaN
7     NaN
dtype: float64

**Sorting based on index**

In [29]:
# sort in ascending order based on index
# sort_index: sorts the series based on the index
# ascending : if specified as True, it sorts values in ascending order (default value is True)
age.sort_index(ascending = True)

0    23.0
1    45.0
2     NaN
3    41.0
4    23.0
5    34.0
6    55.0
7     NaN
8    34.0
9    20.0
dtype: float64

**Rank a Series**

In [30]:
# recall the marks_series
marks_series

Maths             60.0
Science           89.0
Art and Craft     68.0
Social Science    86.0
dtype: float64

In [31]:
# rank the marks in ascending order
# rank(): ranks the values of a series
marks_series.rank()

Maths             1.0
Science           4.0
Art and Craft     2.0
Social Science    3.0
dtype: float64

In [32]:
age.sort_values().rank()

9    1.0
0    2.5
4    2.5
5    4.5
8    4.5
3    6.0
1    7.0
6    8.0
2    NaN
7    NaN
dtype: float64

## DATAFRAME

A DataFrame is a tabular representation of data containing an ordered collection of columns, each of which can be a different type (such as numeric, string, boolean).

The DataFrame has both row and column index; it can be thought of as a dict of Series all sharing the same index. In a data frame, the data is stored as one or more two-dimensional blocks rather than a list, dict, or some other collection of one-dimensional arrays.

While a DataFrame is physically two-dimensional, it can be used to represent higher dimensional data in a tabular format using hierarchical indexing.

### Creating DataFrames

**1. Creating a data frame a dictionary**

In [33]:
# create a dictionary
data = {'Subject': ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art'],
        'Marks': (45, 65, 78, 65, 80, 78),
        'GPA': [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]}

# create the dataframe using DataFrame()
df_data = pd.DataFrame(data)
df_data

    Subject  Marks  GPA
0     Maths     45  2.5
1   History     65  3.0
2   Science     78  3.5
3   English     65  2.0
4  Georaphy     80  4.0
5       Art     78  4.0

In [34]:
# declare the list 'Subject'
Subject = ['Maths', 'History', 'Science', 'English', 'Georaphy', 'Art']

# declare the list 'Marks'
Marks = [45, 65, 78, 65, 80, 78]

# declare the list 'CPA'
GPA = [2.5, 3.0, 3.5, 2.0, 4.0, 4.0]

# create a DataFrame from the lists
# index: specifies the index names
df_marks = pd.DataFrame([Subject, Marks, GPA], index = ['Subject','Marks','GPA'])

# print the DataFrame
df_marks

             0        1        2        3         4    5
Subject  Maths  History  Science  English  Georaphy  Art
Marks       45       65       78       65        80   78
GPA        2.5      3.0      3.5      2.0       4.0  4.0

In [35]:
# transpose the DataFrame
df_marks.T

    Subject Marks  GPA
0     Maths    45  2.5
1   History    65  3.0
2   Science    78  3.5
3   English    65  2.0
4  Georaphy    80  4.0
5       Art    78  4.0

In [36]:
df_data['Marks into GPA'] = df_data['Marks'] * df_data['GPA']
df_data

    Subject  Marks  GPA  Marks into GPA
0     Maths     45  2.5           112.5
1   History     65  3.0           195.0
2   Science     78  3.5           273.0
3   English     65  2.0           130.0
4  Georaphy     80  4.0           320.0
5       Art     78  4.0           312.0

**To read data from csv file**

In [38]:
df_basic_info = pd.read_csv("/content/Disease_Treatment2.csv")
df_basic_info

,Disease,Treatment
0,Apple___Apple_scab,"Use fungicides like captan or mancozeb, prune ..."
1,Apple___Black_rot,"Apply fungicides such as thiophanate-methyl, a..."
2,Apple___Cedar_apple_rust,"Use fungicides like myclobutanil, remove nearb..."
3,Apple___healthy,No treatment required.
4,Blueberry___healthy,No treatment required.
5,Cherry_(including_sour)___Powdery_mildew,"Apply fungicides like sulfur or myclobutanil, ..."
6,Cherry_(including_sour)___healthy,No treatment required.
7,Corn_(maize)___Cercospora_leaf_spot_Gray_leaf_...,"Apply fungicides such as azoxystrobin, rotate ..."
8,Corn_(maize)___Common_rust_,"Use fungicides like mancozeb or copper sprays,..."
9,Corn_(maize)___Northern_Leaf_Blight,"Apply fungicides such as propiconazole, use re..."
10,Corn_(maize)___healthy,No treatment required.
11,Grape___Black_rot,"Apply fungicides like myclobutanil or captan, ..."
12,Grape___Esca_(Black_Measles),"No chemical control available, prune infected ..."
13,Grape___Leaf_blight_(Isariopsis_Leaf_Spot),"Use copper-based fungicides, remove infected l..."
14,Grape___healthy,No treatment required.
15,Orange___Haunglongbing_(Citrus_greening),"No cure available, remove infected trees, cont..."
16,Peach___Bacterial_spot,"Use copper-based bactericides, prune infected ..."
17,Peach___healthy,No treatment required.
18,"Pepper,_bell___Bacterial_spot","Apply copper-based bactericides, remove infect..."
19,"Pepper,_bell___healthy",No treatment required.
20,Potato___Early_blight,Use fungicides like chlorothalonil or mancozeb...
21,Potato___Late_blight,"Apply fungicides such as metalaxyl, remove inf..."
22,Potato___healthy,No treatment required.
23,Raspberry___healthy,No treatment required.
24,Soybean___healthy,No treatment required.
25,Squash___Powdery_mildew,"Use fungicides like sulfur or neem oil, improv..."
26,Strawberry___Leaf_scorch,Apply fungicides such as myclobutanil or coppe...
27,Strawberry___healthy,No treatment required.
28,Tomato___Bacterial_spot,"Use copper-based bactericides, remove infected..."
29,Tomato___Early_blight,"Apply fungicides like chlorothalonil, remove i..."
30,Tomato___Late_blight,"Use fungicides such as metalaxyl, remove infec..."
31,Tomato___Leaf_Mold,"Apply fungicides like chlorothalonil, improve ..."
32,Tomato___Septoria_leaf_spot,"Apply fungicides such as mancozeb, remove infe..."
33,Tomato___Spider_mites_Two-spotted_spider_mite,"Use miticides or insecticidal soaps, increase ..."
34,Tomato___Target_Spot,"Apply fungicides such as azoxystrobin, remove ..."
35,Tomato___Tomato_Yellow_Leaf_Curl_Virus,"Remove infected plants, use insecticides to co..."
36,Tomato___Tomato_mosaic_virus,"Remove infected plants, disinfect tools, contr..."
37,Tomato___healthy,No treatment required.

In [39]:
type(df_basic_info)

pandas.core.frame.DataFrame

In [41]:
df_basic_info.head()

                    Disease                                          Treatment
0        Apple___Apple_scab  Use fungicides like captan or mancozeb, prune ...
1         Apple___Black_rot  Apply fungicides such as thiophanate-methyl, a...
2  Apple___Cedar_apple_rust  Use fungicides like myclobutanil, remove nearb...
3           Apple___healthy                             No treatment required.
4       Blueberry___healthy                             No treatment required.

In [42]:
df_basic_info.tail()

,Disease,Treatment
33,Tomato___Spider_mites_Two-spotted_spider_mite,"Use miticides or insecticidal soaps, increase ..."
34,Tomato___Target_Spot,"Apply fungicides such as azoxystrobin, remove ..."
35,Tomato___Tomato_Yellow_Leaf_Curl_Virus,"Remove infected plants, use insecticides to co..."
36,Tomato___Tomato_mosaic_virus,"Remove infected plants, disinfect tools, contr..."
37,Tomato___healthy,No treatment required.

In [44]:
df_basic_info.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 38 entries, 0 to 37
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Disease    38 non-null     object
 1   Treatment  38 non-null     object
dtypes: object(2)
memory usage: 740.0+ bytes

In [45]:
# to display the shape of the data
df_basic_info.shape

(38, 2)

In [46]:
# to know the type of each variable
df_basic_info.dtypes

Disease      object
Treatment    object
dtype: object